### PR TITLE
init repository

### PR DESCRIPTION
**Pull request by optozorax**

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]
lgtm!

**Comment by ozkriff** [comment]
The PR is currently marked as wip - are you planning to make more changes to it?

**Comment by optozorax** [comment]
Yes, I have plans to more changes, but I will be able to do it after 6 April or slightly later. So, if you think that this is nice starting point, or you want to continue from this, we could merge.

**Comment by ozkriff** [comment]
yeah, it seems useful as it is atm, let's merge

**Review by ozkriff — APPROVED** [review]

**Pull request merged**
